//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BrowserStack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrowserStack() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Resources.BrowserStack", typeof(BrowserStack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browser.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browserName.
        /// </summary>
        internal static string BrowserName {
            get {
                return ResourceManager.GetString("BrowserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browser_version.
        /// </summary>
        internal static string BrowserVersion {
            get {
                return ResourceManager.GetString("BrowserVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to build.
        /// </summary>
        internal static string BuildName {
            get {
                return ResourceManager.GetString("BuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browserstack.key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browserstack.local.
        /// </summary>
        internal static string LocalTesting {
            get {
                return ResourceManager.GetString("LocalTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to device.
        /// </summary>
        internal static string MobileDevice {
            get {
                return ResourceManager.GetString("MobileDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deviceOrientation.
        /// </summary>
        internal static string MobileDeviceOrientation {
            get {
                return ResourceManager.GetString("MobileDeviceOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to os.
        /// </summary>
        internal static string Os {
            get {
                return ResourceManager.GetString("Os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to os_version.
        /// </summary>
        internal static string OsVersion {
            get {
                return ResourceManager.GetString("OsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string TestRunName {
            get {
                return ResourceManager.GetString("TestRunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://hub-cloud.browserstack.com/wd/hub.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browserstack.user.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resolution.
        /// </summary>
        internal static string WindowResolution {
            get {
                return ResourceManager.GetString("WindowResolution", resourceCulture);
            }
        }
    }
}
