//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class TestDataPaths : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestDataPaths defaultInstance = ((TestDataPaths)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestDataPaths())));
        
        public static TestDataPaths Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Framework/Resources/CountriesWithAirports.xml")]
        public string CountriesWithAirports {
            get {
                return ((string)(this["CountriesWithAirports"]));
            }
            set {
                this["CountriesWithAirports"] = value;
            }
        }
    }
}
